theme: jekyll-theme-minimal

title: civet
logo: /doc_figures/civet_logo.png
header_pages:
    - index.md
    - installation.md
    - input_options.md
    - background_data.md
    - usage.md
    - analysis_pipeline.md
    - output.md
    - report_docs.md
    - map_options.md
    - civet_report_example.md
    - acknowledgements.md