name: civet-installation-test
on:
  push:
    branches: [ actions_dev ]
  pull_request:
    branches: [ actions_dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: install dependencies
        run: |
          cd $GITHUB_WORKSPACE/civet
          $CONDA/bin/conda env update --file environment.yml --name base
          
      - name: install civet
        run: |
          cd $GITHUB_WORKSPACE/civet
          python setup.py install
          
      - name: Check version
        run: $CONDA/bin/civet -v
        
